// OPT-05: UI icon sub-barrel
// Icons used by React components (not Phaser)

export { default as Logo } from '../images/icons/nest-logo.svg'
export { default as BellIcon } from '../images/icons/bell-icon.svg'
export { default as ProfileIcon } from '../images/icons/profile-icon.svg'
export { default as HomeIcon } from '../images/icons/home-icon.svg'
export { default as ModuleIcon } from '../images/icons/module-icon.svg'
export { default as SavedIcon } from '../images/icons/saved-icon.svg'
export { default as RewardsIcon } from '../images/icons/rewards-icon.svg'
export { default as ShareIcon } from '../images/icons/share-icon.svg'
export { default as GetHelpIcon } from '../images/icons/get-help-icon.svg'
export { default as SettingsIcon } from '../images/icons/settings-icon.svg'
export { default as SignOutIcon } from '../images/icons/sign-out-icon.svg'
export { default as NestNavigateLogo } from '../images/icons/nest-navigate-logo.svg'
export { default as FacebookIcon } from '../images/icons/facebook.svg'
export { default as TwitterIcon } from '../images/icons/twitter.svg'
export { default as InstagramIcon } from '../images/icons/instagram.svg'
export { default as LinkedInIcon } from '../images/icons/linkedin.svg'
export { default as YouTubeIcon } from '../images/icons/youtube.svg'
export { default as LoadingIcon } from '../images/icons/loading-icon.svg'
export { default as TestResultIcon } from '../images/icons/test-results.svg'
export { default as Confetti } from '../images/icons/confetti.svg'
export { default as CalculatorIcon } from '../images/icons/calculator.svg'
export { default as DocumentIcon } from '../images/icons/document.svg'
export { default as ChecklistIcon } from '../images/icons/checklist.svg'
export { default as ScalesIcon } from '../images/icons/scales.svg'
export { default as ChartIcon } from '../images/icons/chart.svg'
export { default as MaterialHomeIcon } from '../images/icons/home.svg'
export { default as MoneyBoxIcon } from '../images/icons/moneybox.svg'
export { default as SearchIcon } from '../images/icons/search.svg'
export { default as AnalyzeIcon } from '../images/icons/analyze.svg'
export { default as ToDoListIcon } from '../images/icons/todolist.svg'
export { default as CalculatorDarkIcon } from '../images/icons/calculator_dark.svg'
export { default as DocumentDarkIcon } from '../images/icons/document_dark.svg'
export { default as ChecklistDarkIcon } from '../images/icons/checklist_dark.svg'
export { default as ControllerIcon } from '../images/icons/controller.svg'
export { default as ControllerDarkIcon } from '../images/icons/controller_dark.svg'
export { default as Eye } from '../images/icons/Eye.svg'
export { default as Blind } from '../images/icons/Blind.svg'

// Coin Icons
export { default as CoinIcon } from '../images/icons/nest-coin.svg'
export { default as Coin1 } from '../images/icons/coins/coin1.svg'
export { default as Coin2 } from '../images/icons/coins/coin2.svg'
export { default as Coin3 } from '../images/icons/coins/coin3.svg'
export { default as Coin4 } from '../images/icons/coins/coin4.svg'
export { default as Coin5 } from '../images/icons/coins/coin5.svg'
export { default as CoinStack } from '../images/icons/coins/coin_stack.png'
export { default as TreasureChest } from '../images/icons/coins/treasureChest.png'

// Badge Icons
export { default as BadgesIcon } from '../images/icons/badges/badges-icon.svg'
export { default as BadgeFinance } from '../images/icons/badges/badge-finance.svg'
export { default as BadgeHome } from '../images/icons/badges/badge-home.svg'
export { default as BadgeInsurance } from '../images/icons/badges/badge-insurance.svg'
export { default as BadgeNavigation } from '../images/icons/badges/badge-navigation.svg'
export { default as BadgePrize } from '../images/icons/badges/badge-prize.svg'
export { default as BadgeResearch } from '../images/icons/badges/badge-research.svg'
export { default as BadgeRocket } from '../images/icons/badges/badge-rocket.svg'
export { default as BadgeSavings } from '../images/icons/badges/badge-savings.svg'
export { default as BadgeStar } from '../images/icons/badges/badge-star.svg'
export { default as BadgeTrophy } from '../images/icons/badges/badge-trophy.svg'

// Info Colors
export { default as InfoBlue } from '../images/icons/InfoColors/QM_Blue.svg'
export { default as InfoGreen } from '../images/icons/InfoColors/QM_Green.svg'
export { default as InfoPurple } from '../images/icons/InfoColors/QM_Purple.svg'

// Profile Icons
export { default as SettingsProfileIcon } from '../images/icons/profile/settings_icon.png'
export { default as GrowthPointsProfileIcon } from '../images/icons/profile/growthPoints_icon.png'
export { default as NotificationProfileIcon } from '../images/icons/profile/notification_icon.png'
export { default as BadgeProfileIcon } from '../images/icons/profile/badge_icon.png'

// Overview Icons
export { default as StreakBranch } from '../images/icons/overview/streak_branch.png'
export { default as LeaderboardCrown } from '../images/icons/overview/leaderboard-crown.svg'

// Rewards Icons
export { default as CoffeeRewards } from '../images/icons/rewards/coffee_rewards.png'
export { default as TravelRewards } from '../images/icons/rewards/travel_rewards.png'
export { default as ExperienceRewards } from '../images/icons/rewards/experience_rewards.png'
export { default as FoodRewards } from '../images/icons/rewards/food_rewards.png'
export { default as FurnitureRewards } from '../images/icons/rewards/furniture_rewards.png'
export { default as HomeLivingRewards } from '../images/icons/rewards/homeLiving_rewards.png'
export { default as HomeImprovementRewards } from '../images/icons/rewards/homeImprovement_rewards.png'
export { default as MovingRewards } from '../images/icons/rewards/moving_rewards.png'