// Icons
export { default as Logo } from './images/icons/nest-logo.svg'
export { default as CoinIcon } from './images/icons/nest-coin.svg'
export { default as BellIcon } from './images/icons/bell-icon.svg'
export { default as ProfileIcon } from './images/icons/profile-icon.svg'
export { default as HomeIcon } from './images/icons/home-icon.svg'
export { default as ModuleIcon } from './images/icons/module-icon.svg'
export { default as SavedIcon } from './images/icons/saved-icon.svg'
export { default as RewardsIcon } from './images/icons/rewards-icon.svg'
export { default as BadgesIcon } from './images/icons/badges-icon.svg'
export { default as ShareIcon } from './images/icons/share-icon.svg'
export { default as GetHelpIcon } from './images/icons/get-help-icon.svg'
export { default as SettingsIcon } from './images/icons/settings-icon.svg'
export { default as SignOutIcon } from './images/icons/sign-out-icon.svg'
export { default as NestNavigateLogo } from './images/icons/nest-navigate-logo.svg'
export { default as FacebookIcon } from './images/icons/facebook.svg'
export { default as TwitterIcon } from './images/icons/twitter.svg'
export { default as InstagramIcon } from './images/icons/instagram.svg'
export { default as LinkedInIcon } from './images/icons/linkedin.svg'
export { default as YouTubeIcon } from './images/icons/youtube.svg'
export { default as LoadingIcon } from './images/icons/loading-icon.svg'
export { default as TestResultIcon } from './images/icons/test-results.svg'
export { default as Coin1} from './images/icons/coins/coin1.svg'
export { default as Coin2} from './images/icons/coins/coin2.svg'
export { default as Coin3} from './images/icons/coins/coin3.svg'
export { default as Coin4} from './images/icons/coins/coin4.svg'
export { default as Coin5} from './images/icons/coins/coin5.svg'
export { default as Confetti } from './images/icons/confetti.svg'
export {default as BadgeMedal } from './images/icons/badge.svg'
export { default as CalculatorIcon } from './images/icons/calculator.svg'
export { default as DocumentIcon } from './images/icons/document.svg'
export { default as ChecklistIcon } from './images/icons/checklist.svg'
// Static Images
export { default as SignupImage } from './images/static/signup_page.png'
export { default as LoginImage } from './images/static/login_page.png'
export { default as CelebrationImage } from './images/static/celebration-image.png'
export { default as QuestionImage } from './images/static/question_image.png'
export { default as TryAgainImage } from './images/static/tryagain-image.png'
